name: flutter_proj
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.2
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
